/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Transport;

import Business.Network.MarketNews;
import Business.Network.Product;
import Business.Organization.TransportOrganization;
import Business.UserAccount.FarmerUserAccount;
import Business.UserAccount.UserAccount;
import Business.Utility;
import Business.WorkQueue.ProducePickUpRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author abdusamed
 */
public class TransportDriverWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    UserAccount driverAccount;
    TransportOrganization organization;
    

    /**
     * Creates new form TransportDriverWorkAreaJPanel
     */
    
    public TransportDriverWorkAreaJPanel(JPanel userProcessContainer, TransportOrganization organization, UserAccount driverAccount) {
        initComponents();
        this.driverAccount = driverAccount;
        this.organization = organization;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJobAssigned = new javax.swing.JTable();
        UpdateJobs = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setText("Jobs Assigned To You");

        tblJobAssigned.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Farmer Name", "Farmer Address", "Date Pickup", "Drop Off Locaition", "Truck Size", "Status", "Produce"
            }
        ));
        jScrollPane1.setViewportView(tblJobAssigned);

        UpdateJobs.setText("Job Completed");
        UpdateJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateJobsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Transport Driver Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(UpdateJobs))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(374, 433, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateJobs)
                .addGap(94, 94, 94))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateJobsActionPerformed
        // TODO add your handling code here:

        int seletectedRow = tblJobAssigned.getSelectedRow();
        if(seletectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select Job Assigned to Process", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            String statusCheck = (String) tblJobAssigned.getValueAt(seletectedRow, 5);
            ProducePickUpRequest producePickUpRequest = (ProducePickUpRequest) tblJobAssigned.getValueAt(seletectedRow,6);
            producePickUpRequest.setStatus("Goods have been dropped - By Driver");
            
            JOptionPane.showMessageDialog(null, "Job Status Updated. Thank you.", "Success", JOptionPane.OK_OPTION);
            
            
            MarketNews marketNews = new MarketNews();
            marketNews.setDateAnnounced(Utility.getCurrentDate());
            marketNews.setNewsDetail("Driver has dropped your produce at: " + producePickUpRequest.getDropOffLocation());
            marketNews.setNewsSubject("Produce Delivery by Trucker");
            Product product = producePickUpRequest.getProduct();
            marketNews.setProduct(product);
            ((FarmerUserAccount)producePickUpRequest.getSender()).getMessageList().add(marketNews);
            
            JOptionPane.showMessageDialog(null, "Job Status Updated. Thank you.", "Success", JOptionPane.OK_OPTION);


            }
        

    }//GEN-LAST:event_UpdateJobsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateJobs;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJobAssigned;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblJobAssigned.getModel();
        dtm.setRowCount(0);
        for(WorkRequest request: organization.getWorkQueue().getWorkRequestList()){
            if(request.getReceiver().equals(driverAccount)){
                ProducePickUpRequest pickUpRequest = (ProducePickUpRequest) request;
                Object[] row = new Object[7];
                row[0] = pickUpRequest.getSender();
                row[1] = ((FarmerUserAccount) pickUpRequest.getSender()).getAddress();
                row[2] = pickUpRequest.getPickupDate();
                row[3] = pickUpRequest.getDropOffLocation();
                row[4] = pickUpRequest.getTruckSize();
                row[5] = pickUpRequest.getStatus();
                row[6] = pickUpRequest;
                dtm.addRow(row);
            }
        }
    }
}
