/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Finance;

import Business.Enterprise.Enterprise;
import Business.Enterprise.FarmerEnterprise;
import Business.Network.MarketNews;
import Business.Network.Network;
import Business.Organization.FarmerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.FarmerUserAccount;
import Business.UserAccount.UserAccount;
import Business.Utility;
import Business.WorkQueue.LoanRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abdusamed
 */
public class FinanceLoanWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    UserAccount account;
    Network network;
    int year = 2017;int month = 12;int day = 13;
    Date date = new Date(year, month, day);
    /**
     * Creates new form FinanceManagerWorkAreaJPanel
     */
    public FinanceLoanWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.network = network;
        populateLoanTable();
    }
    
    public void populateLoanTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblLoanTable.getModel();
        dtm.setRowCount(0);
        for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
            if(enterprise instanceof FarmerEnterprise){
                for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(organization instanceof FarmerOrganization){
                            for(UserAccount farmerUserAccount : organization.getUserAccountDirectory().getUserAccountList()){
                                if(farmerUserAccount instanceof FarmerUserAccount){
                                    for(LoanRequest loanRequest:((FarmerUserAccount) farmerUserAccount).getFinanceWorkQueue()){
                                        Object[] row = new Object[8];
                                        row[0] = farmerUserAccount;
                                        row[1] = ((FarmerUserAccount) farmerUserAccount).getAddress();
                                        row[2] = loanRequest;
                                        row[3] = loanRequest.getLoanAmount();
                                        row[4] = loanRequest.getStatus();
                                        row[5] = account.getEmployee().getName();
                                        row[6] = loanRequest.getRequestDate();
                                        Date date = loanRequest.getResolveDate();
                                        row[7] = date == null ? "Not Processed" : date;
                                        dtm.addRow(row);
                                    }
                                }
                            }
                    }
                }
            }
        }        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoanTable = new javax.swing.JTable();
        btnReject = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCancelRequest1 = new javax.swing.JButton();

        tblLoanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Farmer Name", "Farmer Address", "Loan Detail", "Loan Amount", "Loan Status", "Bank Manager", "Date Created", "Date Resolved"
            }
        ));
        jScrollPane2.setViewportView(tblLoanTable);

        btnReject.setText("Reject Loan");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnApprove.setText("Approve Loan");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Finance Manager Work Area");

        btnCancelRequest1.setText("Back");
        btnCancelRequest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRequest1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnApprove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelRequest1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnApprove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReject)
                .addGap(18, 18, 18)
                .addComponent(btnCancelRequest1)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        int seletectedRow = tblLoanTable.getSelectedRow();
        if(seletectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row from the Table", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            
            LoanRequest loanRequest = (LoanRequest) tblLoanTable.getValueAt(seletectedRow, 2);
            loanRequest.setReceiver(account);
            loanRequest.setStatus("Approved - By Finance!");
            loanRequest.setResolveDate(date);
            
            MarketNews marketNews = new MarketNews();
            marketNews.setDateAnnounced(Utility.getCurrentDate());
            marketNews.setNewsDetail("Congrats. Your request for loan has been approved.");
            marketNews.setNewsSubject("Finance Loan Status");
            
            ((FarmerUserAccount)loanRequest.getSender()).getMessageList().add(marketNews);
            
            JOptionPane.showMessageDialog(null, "Loan Status has changed to Approved!", "Loan Update!", JOptionPane.OK_OPTION);

        }
        populateLoanTable();
        
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int seletectedRow = tblLoanTable.getSelectedRow();
        if(seletectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row from the Table", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            
            LoanRequest loanRequest = (LoanRequest) tblLoanTable.getValueAt(seletectedRow, 2);
            loanRequest.setReceiver(account);
            loanRequest.setStatus("Rejected - By Finance");
            loanRequest.setResolveDate(Utility.getCurrentDate());
            System.out.println("Loan Status Rejected");
            
            MarketNews marketNews = new MarketNews();
            marketNews.setDateAnnounced(Utility.getCurrentDate());
            marketNews.setNewsDetail("Sorry. Your request for loan has been REJECTED.");
            marketNews.setNewsSubject("Finance Loan Status");
            
            ((FarmerUserAccount)loanRequest.getSender()).getMessageList().add(marketNews);
            
            JOptionPane.showMessageDialog(null, "Loan Status has changed to Rejected!", "Loan Update!", JOptionPane.OK_OPTION);
            
        }
        populateLoanTable();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnCancelRequest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRequest1ActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FinanceManagerWorkAreaJPanel dwjp = (FinanceManagerWorkAreaJPanel) component;
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnCancelRequest1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnCancelRequest1;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblLoanTable;
    // End of variables declaration//GEN-END:variables
}
