/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Farmer;

import Business.UserAccount.FarmerUserAccount;
import Business.Utility;
import Business.WorkQueue.LoanRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abdusamed
 */
public class FarmerFinanceWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private FarmerUserAccount account;
    
//    private 

    /**
     * Creates new form FarmerFinanceWorkAreaJPanel
     */
    FarmerFinanceWorkAreaJPanel(JPanel userProcessContainer, FarmerUserAccount account) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.account = account;
       
       populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        requestTestJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtloanAmount = new javax.swing.JTextField();
        buttonSimpleBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoanHistory = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Farmer Finance Dashboard");

        jLabel3.setText("Request Loan Amount");

        requestTestJButton.setText("Request MicroLoan");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        textAreaDescription.setColumns(20);
        textAreaDescription.setFont(textAreaDescription.getFont());
        textAreaDescription.setLineWrap(true);
        textAreaDescription.setRows(5);
        jScrollPane1.setViewportView(textAreaDescription);

        jLabel4.setText("Loan Description");

        txtloanAmount.setText("Enter Amount");
        txtloanAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtloanAmountMouseClicked(evt);
            }
        });
        txtloanAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloanAmountActionPerformed(evt);
            }
        });

        buttonSimpleBack.setText("Back");
        buttonSimpleBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpleBackActionPerformed(evt);
            }
        });

        tblLoanHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Loan Detail", "Loan Amount", "Date Requested", "Status", "Resolved By", "Resolved On"
            }
        ));
        jScrollPane2.setViewportView(tblLoanHistory);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("Request New Loan");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("Your Loan Request History");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(254, 254, 254))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtloanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(requestTestJButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSimpleBack, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtloanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestTestJButton))
                .addGap(31, 31, 31)
                .addComponent(buttonSimpleBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        if(!textAreaDescription.getText().isEmpty() && Utility.intCheck(txtloanAmount.getText())){
        LoanRequest request = new LoanRequest();
        request.setLoanDescription(textAreaDescription.getText());
        request.setLoanAmount(Integer.parseInt(txtloanAmount.getText()));
        request.setRequestDate(Utility.getCurrentDate());
        request.setStatus("Pending");
        
        account.getFinanceWorkQueue().add(request);
        System.out.println("Loan Queue Added");
        
        populateTable();
        
        JOptionPane.showMessageDialog(null, "Loan Request Submitted", "Success!", JOptionPane.OK_OPTION);
        
        }else{
            JOptionPane.showMessageDialog(null, "Invalid Entry. Please Try Again", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void txtloanAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloanAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloanAmountActionPerformed

    private void txtloanAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtloanAmountMouseClicked
        // TODO add your handling code here:
        txtloanAmount.setText("");
    }//GEN-LAST:event_txtloanAmountMouseClicked

    private void buttonSimpleBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpleBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        
        Component component = componentArray[componentArray.length - 1];
        FarmerFarmerWorkAreaJPanel dwjp = (FarmerFarmerWorkAreaJPanel) component;
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_buttonSimpleBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSimpleBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTable tblLoanHistory;
    private javax.swing.JTextArea textAreaDescription;
    private javax.swing.JTextField txtloanAmount;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblLoanHistory.getModel();
        dtm.setRowCount(0);

        for (LoanRequest request : account.getFinanceWorkQueue()){
            Object[] row = new Object[6];
            row[0] = request.getLoanDescription();
            row[1] = request.getLoanAmount();
            row[2] = request.getRequestDate();
            row[3] = request.getStatus();
            row[4] = request.getReceiver();
            row[5] = request.getResolveDate();            
            dtm.addRow(row);
        }
    }
}
