/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Farmer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.MarketNews;
import Business.Network.Network;
import Business.Organization.FarmerOrganization;
import Business.UserAccount.FarmerUserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author abdusamed
 */
public class FarmerFarmerWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private FarmerUserAccount account;
    private FarmerOrganization organization;
    private Enterprise enterprise;
    private EcoSystem busines;
    private Network network;

    /**
     * Creates new form FarmerFarmerWorkAreaJPanel
     */
    public FarmerFarmerWorkAreaJPanel(JPanel userProcessContainer, FarmerUserAccount account, FarmerOrganization organization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.busines = business;
        this.network = network;        
        
        populateFarmerNews();
        popTextBox();
        
        
    }
    
    public void populateFarmerNews(){
//    StringBuilder farmReport = new StringBuilder();
    jtxtMessageBoard.setText(null);
    ArrayList<MarketNews> mnd = account.getMessageList();
    if(mnd != null){
        for(MarketNews news : account.getMessageList()){
            jtxtMessageBoard.append("*********************************************************************************************************\n");
            jtxtMessageBoard.append("||Subject: " + news.getNewsSubject()+ "|| Detail: " + news.getNews() + "|| Date -> " + news.getDateAnnounced() + "\n");
            jtxtMessageBoard.append("*********************************************************************************************************\n");
            
                //+ " -> For Product -> " + news.getProduct().getProductType().getValue()
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFinanceWorkArea = new javax.swing.JButton();
        btnChemicalWorkArea = new javax.swing.JButton();
        btnTransportWorkArea = new javax.swing.JButton();
        btnHospitalWorkArea = new javax.swing.JButton();
        btnMarketWorkArea = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtMessageBoard = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtFarmerName = new javax.swing.JLabel();

        jLabel1.setText("Farmer Farmer WorkArea JPanel");

        btnFinanceWorkArea.setText("Finance WorkArea");
        btnFinanceWorkArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceWorkAreaActionPerformed(evt);
            }
        });

        btnChemicalWorkArea.setText("Chemical WorkArea");
        btnChemicalWorkArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChemicalWorkAreaActionPerformed(evt);
            }
        });

        btnTransportWorkArea.setText("Transport WorkArea");
        btnTransportWorkArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransportWorkAreaActionPerformed(evt);
            }
        });

        btnHospitalWorkArea.setText("Hospital WorkArea");
        btnHospitalWorkArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalWorkAreaActionPerformed(evt);
            }
        });

        btnMarketWorkArea.setText("Market WorkArea");
        btnMarketWorkArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarketWorkAreaActionPerformed(evt);
            }
        });

        jtxtMessageBoard.setEditable(false);
        jtxtMessageBoard.setColumns(20);
        jtxtMessageBoard.setRows(5);
        jScrollPane1.setViewportView(jtxtMessageBoard);

        jLabel2.setText("Welcome: ");

        txtFarmerName.setText("<Farmer Name>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTransportWorkArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFinanceWorkArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMarketWorkArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChemicalWorkArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHospitalWorkArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtFarmerName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFarmerName))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChemicalWorkArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMarketWorkArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinanceWorkArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransportWorkArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHospitalWorkArea)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinanceWorkAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceWorkAreaActionPerformed
        // TODO add your handling code here:
        FarmerFinanceWorkAreaJPanel farmerfinancewajp = new FarmerFinanceWorkAreaJPanel(userProcessContainer, account);
        userProcessContainer.add("farmerfinancewajp", farmerfinancewajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnFinanceWorkAreaActionPerformed

    private void btnTransportWorkAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransportWorkAreaActionPerformed
        // TODO add your handling code here:
        FarmerTransportWorkAreaJPanel farmerTransportJPanel = new FarmerTransportWorkAreaJPanel(userProcessContainer, account);
        userProcessContainer.add("FTwjp", farmerTransportJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnTransportWorkAreaActionPerformed

    private void btnHospitalWorkAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalWorkAreaActionPerformed
        // TODO add your handling code here:
        FarmerHospitalWorkAreaJPanel farmerHospitalJPanel = new FarmerHospitalWorkAreaJPanel(userProcessContainer, account, network);
        userProcessContainer.add("FHwjp", farmerHospitalJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnHospitalWorkAreaActionPerformed

    private void btnMarketWorkAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarketWorkAreaActionPerformed
        // TODO add your handling code here:
        FarmerMarketJPanel farmerMarketJPanel = new FarmerMarketJPanel(userProcessContainer, account, network);
        userProcessContainer.add("FMwajp", farmerMarketJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMarketWorkAreaActionPerformed

    private void btnChemicalWorkAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChemicalWorkAreaActionPerformed
        // TODO add your handling code here:
        FarmerChemicalWorkAreaJPanel farmerChemicalJPanel = new FarmerChemicalWorkAreaJPanel(userProcessContainer, account);
        userProcessContainer.add("FCwaj", farmerChemicalJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnChemicalWorkAreaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChemicalWorkArea;
    private javax.swing.JButton btnFinanceWorkArea;
    private javax.swing.JButton btnHospitalWorkArea;
    private javax.swing.JButton btnMarketWorkArea;
    private javax.swing.JButton btnTransportWorkArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtxtMessageBoard;
    private javax.swing.JLabel txtFarmerName;
    // End of variables declaration//GEN-END:variables

    private void popTextBox() {
        txtFarmerName.setText(account.getEmployee().getName());
    }

}
