/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Farmer;

import Business.Network.MarketNews;
import Business.Network.Network;
import Business.Network.Product;
import Business.UserAccount.FarmerUserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abdusamed
 */
public class FarmerMarketJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private FarmerUserAccount account;
    private Network network;

    /**
     * Creates new form FarmerMarketJPanel
     */

    FarmerMarketJPanel(JPanel userProcessContainer, FarmerUserAccount account, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.network = network;
        populateTextBox();
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaDisplayNews = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProducePrice = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Farmer Market WorkArea JPanel");

        jtxtAreaDisplayNews.setColumns(20);
        jtxtAreaDisplayNews.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaDisplayNews);

        jLabel2.setText("News Directly From the Market");

        tblProducePrice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Produce", "Price", "Month"
            }
        ));
        tblProducePrice.setEnabled(false);
        jScrollPane2.setViewportView(tblProducePrice);

        jLabel4.setText("Current Trending Sales in Market");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void populateTextBox(){
//        StringBuilder newsReport = new StringBuilder();
        jtxtAreaDisplayNews.setText(null);
        
        for(MarketNews news:network.getMarketNewsDirectory().getMarketNewsDirectory()){
            //jtxtAreaDisplayNews.append(news.getNews() + "--> Published On --> " + news.getDateAnnounced());
            jtxtAreaDisplayNews.append(news.getNewsSubject() + " " + news.getNewsDetail()+ " For: " + news.getProduct().getProductType() + "Date: " + news.getDateAnnounced()+"\n");
        }       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jtxtAreaDisplayNews;
    private javax.swing.JTable tblProducePrice;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblProducePrice.getModel();
        dtm.setRowCount(0);

        for (Product product : network.getProductDirectory().getProductList()){
            Object[] row = new Object[3];
            row[0] = product;
            row[1] = product.getRate();
            row[2] = product.getProductMonth().getValue();
            dtm.addRow(row);
            }
    }
}
